apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: IMAGE_NAME:IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: spring-petclinic
              key: IMAGE_NAME
        - name: IMAGE_TAG
          valueFrom:
            configMapKeyRef:
              name: spring-petclinic
              key: IMAGE_TAG
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

